swagger: "2.0"
info:
  title: "ChickenGuard"
  description: ""
  version: "1.0.0"
tags:
- name: "Weather"
  description: "Information about weather"
- name: "Fan"
  description: "Control fan"
produces:
- "application/json"
paths:
  /api/healtz:
    get:
      tags:
      - "Health"
      description: "Get application health status"
      operationId: "getHealth"
      responses:
        200:
          description: "Service healthy"
  /api/weather/current:
    get:
      tags:
      - "Weather"
      description: "Get current weather"
      operationId: "getCurrentWeather"
      responses:
        200:
          description: "Current weather"
          schema:
            type: "object"
            $ref: "#/definitions/Weather"

  /api/fan/start:
    post:
      tags:
      - "Fan"
      description: "Start fan"
      operationId: "startFan"
      responses:
        200:
          description: "Fan started"

  /api/fan/stop:
    post:
      tags:
      - "Fan"
      description: "Stop fan"
      operationId: "stopFan"
      responses:
        200:
          description: "Fan stopped"

definitions:
  Weather:
    type: "object"
    properties:
      temperature:
        type: "number"
      humidity:
        type: "number"
